name: Code Review Action

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Code Review Action
        uses: sarfraznawaz2005/ai-code-review-action@main
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          email-host: "mail.eteamid.com"
          email-port: "465"
          email-user: "mr-x@eteamid.com"
          email-pass: "8gxe#71b`GIb"
          email-from: "CodeReview <mr-x@eteamid.com>"
          email-to: "sarfraz@eteamid.com"
          email-secure: "true"
